### ISSUE TITLE
Expected content: auto

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/distributed-navigation#1]
Markbot is almost happy except this one value expected somewhere in the code: **auto**

I'm just not sure what CSS property **auto** belongs to in this flexbox exercise.

@thomasjbradley

**Comment by thomasjbradley** [comment]
I’m using it on `margin` to ”automatically” push things away.

**Comment by C-G-G** [comment]
I added it to `<p>` to center the element on the page.
